milestone 3: project Association setup
bronnie313/OOP-school-library pull request #3
Opened 2023-07-27 15:34 UTC by bronnie313

## OOP school library: set up associations

- [ ] Created class Classroom and initialized label as an instance variable and also defined its setter and getter
- [ ] Created a relationship between the  classroom and the Student 
- [ ] Created a class Book and initialized the title and author as its instance variables and created the setter and getter for them
- [ ] Created a class Rental and initialized the date as its instance variable and also defined the setter and getter for the date
- [ ] Created association setup between the person, Book and the rental

2023-07-27 16:03 UTC, DeliceLydia requested changes
## Hi @bronnie313, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Followed git workflow
- No linter errors


## Required Changes ♻️
_Check the comments under the review._



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 16:03 UTC, DeliceLydia commented on rental.rb
> +    book.add_rental(self)
- [ ] This should be `book.rentals << self` The rental is adding itself to the `@person` the 'belongs-to' association

2023-07-27 16:03 UTC, DeliceLydia commented on person.rb
> +  end
- [ ] in the `person` class the person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
```ruby
  def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2023-07-28 11:11 UTC, mckent05 requested changes
Hi @bronnie313, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/207265397-5ef597f5-a50c-49b4-8f07-7548b0520e98.gif)


 ## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job setting up associations between your classes 👏 👏 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 11:11 UTC, mckent05 commented on student.rb
> +    classroom.students.push(self)
- Good job creating a custom setter, but in order to prevent adding the same student to one class please include this condition ` classroom.students.push(self) unless classroom.students.include?(self)`

2023-07-28 11:11 UTC, mckent05 commented on rental.rb
> +    @book = book
**OPTIONAL** - You may have misunderstood the previous reviewer when she said you didn't need to initialize the date attribute. Please add back the date instance variable as it is a part of the project requirements 🙏

2023-07-28 11:11 UTC, mckent05 commented on person.rb
> +  end
- Please implement the `has-many` association as suggested by the previous reviewer. Please fix this 👍 👍

2023-07-28 11:11 UTC, mckent05 commented on book.rb
> +    @rentals << rental
- This action is already performed in the rental instance you created above, to avoid adding duplicate data in the rental array, I suggest removing this line of code. Please fix this 🙏

2023-07-28 11:57 UTC, shella12 approved these changes
Hi @bronnie313, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Added all associations✔️ 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 11:58 UTC, merged